import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';
import { catchError, map, Observable, throwError } from 'rxjs';
import { ExpenseApplicationError, ExpenseErrorKind } from '../../application/expense.errors';
import { CreateSettlementCommand, DebtSummary, ExpensePagination, MonthlyFinancialSummary, SettlementFilters, SettlementPage } from '../../application/expense.models';
import { FinancialGateway, SettlementGateway } from '../../application/ports/financial.gateway';
import { HouseholdRef, Settlement, SettlementId } from '../../domain';
import { mapDebtSummary, mapMonthlySummary, mapSettlement, mapSettlementPage } from './financial-api.mapper';
export class HttpFinancialGateway implements FinancialGateway, SettlementGateway {
  constructor(private readonly http: HttpClient, private readonly apiUrl: string) {}
  getMonthly(householdId: HouseholdRef, month: string): Observable<MonthlyFinancialSummary> { return this.http.get<unknown>(`${this.household(householdId)}/financial-summary/monthly`, { params: new HttpParams().set('month', month) }).pipe(map(mapMonthlySummary), this.errors()); }
  getDebt(householdId: HouseholdRef): Observable<DebtSummary> { return this.http.get<unknown>(`${this.household(householdId)}/debt-summary`).pipe(map(mapDebtSummary), this.errors()); }
  list(householdId: HouseholdRef, filters: SettlementFilters, pagination: ExpensePagination): Observable<SettlementPage> { let params = new HttpParams().set('page', pagination.page).set('size', pagination.size); if (filters.from) params = params.set('from', filters.from); if (filters.to) params = params.set('to', filters.to); if (filters.status) params = params.set('status', filters.status); if (filters.memberId) params = params.set('memberId', filters.memberId); return this.http.get<unknown>(this.settlements(householdId), { params }).pipe(map(mapSettlementPage), this.errors()); }
  get(householdId: HouseholdRef, id: SettlementId): Observable<Settlement> { return this.http.get<unknown>(`${this.settlements(householdId)}/${id}`).pipe(map(mapSettlement), this.errors()); }
  create(householdId: HouseholdRef, command: CreateSettlementCommand): Observable<Settlement> { const body: Record<string, unknown> = { fromMemberId: command.fromMemberId, toMemberId: command.toMemberId, amount: command.amount.toDecimal(), currency: command.amount.currency, settlementDate: command.settlementDate }; if (command.note) body['note'] = command.note; return this.http.post<unknown>(this.settlements(householdId), body, { headers: { 'Idempotency-Key': command.idempotencyKey } }).pipe(map(mapSettlement), this.errors()); }
  void(householdId: HouseholdRef, id: SettlementId, reason: string): Observable<Settlement> { return this.http.post<unknown>(`${this.settlements(householdId)}/${id}/void`, { reason }).pipe(map(mapSettlement), this.errors()); }
  private household(id: HouseholdRef): string { return `${this.apiUrl}/households/${id}`; } private settlements(id: HouseholdRef): string { return `${this.household(id)}/settlements`; }
  private errors<T>(): (source: Observable<T>) => Observable<T> { return source => source.pipe(catchError((failure: unknown) => throwError(() => normalize(failure)))); }
}
const normalize = (failure: unknown): ExpenseApplicationError => { if (failure instanceof ExpenseApplicationError) return failure; if (!(failure instanceof HttpErrorResponse)) return new ExpenseApplicationError('unexpected', 'Unexpected error'); const kinds: Readonly<Record<number, ExpenseErrorKind>> = { 0: 'network', 400: 'validation', 401: 'unauthenticated', 403: 'forbidden', 404: 'not-found', 409: 'conflict' }; const body = typeof failure.error === 'object' && failure.error !== null ? failure.error as Readonly<Record<string, unknown>> : {}; const fields = typeof body['fields'] === 'object' && body['fields'] !== null ? body['fields'] as Readonly<Record<string, string>> : {}; return new ExpenseApplicationError(kinds[failure.status] ?? 'unexpected', typeof body['message'] === 'string' ? body['message'] : failure.message, fields); };
