import { Component, DestroyRef, effect, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';import { ActivatedRoute, Router, RouterLink } from '@angular/router';import { TranslatePipe } from '@ngx-translate/core';
import { LocalizedCurrencyPipe } from '../../../../core/i18n/localized-format.pipe';import { ButtonComponent } from '../../../../shared/components/button/button.component';import { CardComponent } from '../../../../shared/components/card/card.component';import { EmptyStateComponent } from '../../../../shared/components/empty-state/empty-state.component';import { HouseholdStore } from '../../../household';import { Money } from '../../domain';import { FinancialSummaryStore } from './financial-summary.store';
@Component({selector:'app-financial-summary',imports:[RouterLink,TranslatePipe,LocalizedCurrencyPipe,ButtonComponent,CardComponent,EmptyStateComponent],templateUrl:'./financial-summary.component.html'})
export class FinancialSummaryComponent {
 protected readonly household=inject(HouseholdStore);protected readonly store=inject(FinancialSummaryStore);private readonly route=inject(ActivatedRoute);private readonly router=inject(Router);private readonly destroyRef=inject(DestroyRef);protected readonly month=signal(localMonth());
 constructor(){this.route.queryParamMap.pipe(takeUntilDestroyed(this.destroyRef)).subscribe(params=>{const value=params.get('month');this.month.set(value&&/^\d{4}-(0[1-9]|1[0-2])$/.test(value)?value:localMonth());this.reload();});effect(()=>{this.household.active()?.id;this.reload();});}
 protected reload():void{const id=this.household.active()?.id;if(id)void this.store.load(id,this.month());else this.store.reset();}protected changeMonth(value:string):void{if(/^\d{4}-(0[1-9]|1[0-2])$/.test(value))void this.router.navigate([],{relativeTo:this.route,queryParams:{month:value===localMonth()?null:value},queryParamsHandling:'merge'});}
 protected memberName(id:string):string{return this.household.active()?.members.find(m=>m.id===id)?.email??`${id.slice(0,8)}…`;}protected positionKey(money:Money):string{return money.isPositive()?'financial.receive':money.isNegative()?'financial.pay':'financial.settled';}protected canSettle(from:string,to:string):boolean{const active=this.household.active();const summary=this.household.households().find(h=>h.id===active?.id);return summary?.currentRole==='ADMIN'||summary?.currentMemberId===from||summary?.currentMemberId===to;}
}
const localMonth=():string=>{const now=new Date();return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;};
